uploads = []
outputs = []

[[generated]]
id = "Gt5LvAnss3FomVxHz0LBf"
uri = "file://artifacts/rudhra-library/src/assets/hero.png"
type = "image"
title = "Library Hero Image"

[[generated]]
id = "RtbPT3FchnupX4l9J2M5y"
uri = "file://artifacts/rudhra-library/src/assets/cubicle.png"
type = "image"
title = "Study Cubicle"

[[generated]]
id = "3dw7ya4W-9OxtC7NoTRd-"
uri = "file://artifacts/rudhra-library/src/assets/books.png"
type = "image"
title = "Books and light"

[[generated]]
id = "du6j_YX2TlBi2Vf3guMrW"
uri = "file://artifacts/rudhra-library/src/assets/rudhra-logo.png"
type = "image"
title = "Rudhra Library logo"
